name: deploy-container

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run build

      - uses: reggionick/s3-deploy@v4
        with:
          folder: ./packages/container/dist
          bucket: ${{ secrets.AWS_S3_BUCKET }}/container/latest
          bucket-region: 'us-east-1'
          dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
          invalidation: '/container/latest/index.html'
          delete-removed: true
